version: '3'
services:
  drools-workbench:
    build:
        context: ./drools
        dockerfile: Dockerfile
    image: quay.io/kiegroup/kie-drools-wb:7.74.1.Final
    ports:
      - 8080:8080
      - 9990:9990

  kie-server:
    build:
        context: ./kie-server
        dockerfile: Dockerfile
    ports:
      - 8082:8080
      - 9992:9990